// yt-playlist-organizer-vue/src/components/ButtonToggle.vue
<template>
    <button 
        class="border border-black rounded pl-1 pr-1 m-0.5 focus:outline-none"
        :class="{ 'bg-blue-700': checked, 'text-white': checked }"
        v-on:click="onClick()">
        {{name}}
    </button>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  props: {
    name: String,
  },
  data (): { checked: boolean; } {
    return {
      checked: false
    }
  },
  name: "ButtonToggle",
  methods: {
    onClick: function () {
        this.checked = !this.checked;
        this.$emit('toggleChanged', this.checked)
    }
  }
});
</script>

// yt-playlist-organizer/src/app/shared/button-toggle/button-toggle.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-button-toggle',
  templateUrl: './button-toggle.component.html',
  styleUrls: ['./button-toggle.component.scss']
})
export class ButtonToggleComponent implements OnInit {
  @Input() name: string;
  @Output() toggleChanged = new EventEmitter<boolean>();
  
  public checked: boolean = false;

  constructor() { }

  ngOnInit(): void {
  }

  public onClick(): void {
    this.checked = !this.checked;
    this.toggleChanged.emit(this.checked)
  }
}

<button class="border border-black rounded pl-1 pr-1 m-0.5 focus:outline-none"
    [ngClass]="{ 'bg-blue-700': checked, 'text-white': checked }" (click)="onClick()">
    {{name}}
</button>
